name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3
      with:
        jvm: temurin:17
    - name: Compile
      run: ./mill __.compile

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3
      with:
        jvm: 8
        apps: scalafmt:3.1.1
    - run: scalafmt --check

  publish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3
      with:
        jvm: temurin:17
    - run: .github/scripts/gpg-setup.sh
      env:
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
    - name: Release
      run: ./mill -i publishSonatype __.publishArtifacts
      env:
        PGP_PASSPHRASE: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
